name: b128b282-dee7-44a7-bc21-f1fd21452a83
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9
  - pystac-client==0.7.6
  - odc-stac==0.3.9
  - jupyter
  - geopandas
  - rioxarray==0.15.0
  - rasterstats==0.19.0
  - hvplot
  - datashader
  - scikit-learn
  - geoviews==1.11.1
